---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - external-secrets.io
  resources:
  - externalsecrets
  verbs:
  - create
  - get
  - list
  - update
- apiGroups:
  - nexus.kostoed.ru
  resources:
  - contentselectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nexus.kostoed.ru
  resources:
  - contentselectors/finalizers
  verbs:
  - update
- apiGroups:
  - nexus.kostoed.ru
  resources:
  - contentselectors/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nexus.kostoed.ru
  resources:
  - nexusconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nexus.kostoed.ru
  resources:
  - nexusconfigurations/finalizers
  verbs:
  - update
- apiGroups:
  - nexus.kostoed.ru
  resources:
  - nexusconfigurations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nexus.kostoed.ru
  resources:
  - nexusteamaccesses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nexus.kostoed.ru
  resources:
  - nexusteamaccesses/finalizers
  verbs:
  - update
- apiGroups:
  - nexus.kostoed.ru
  resources:
  - nexusteamaccesses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nexus.kostoed.ru
  resources:
  - nexusteambindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nexus.kostoed.ru
  resources:
  - nexusteambindings/finalizers
  verbs:
  - update
- apiGroups:
  - nexus.kostoed.ru
  resources:
  - nexusteambindings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nexus.kostoed.ru
  resources:
  - nexususers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nexus.kostoed.ru
  resources:
  - nexususers/finalizers
  verbs:
  - update
- apiGroups:
  - nexus.kostoed.ru
  resources:
  - nexususers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nexus.kostoed.ru
  resources:
  - privileges
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nexus.kostoed.ru
  resources:
  - privileges/finalizers
  verbs:
  - update
- apiGroups:
  - nexus.kostoed.ru
  resources:
  - privileges/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nexus.kostoed.ru
  resources:
  - repositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nexus.kostoed.ru
  resources:
  - repositories/finalizers
  verbs:
  - update
- apiGroups:
  - nexus.kostoed.ru
  resources:
  - repositories/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nexus.kostoed.ru
  resources:
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nexus.kostoed.ru
  resources:
  - roles/finalizers
  verbs:
  - update
- apiGroups:
  - nexus.kostoed.ru
  resources:
  - roles/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nexus.kostoed.ru
  resources:
  - routingrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nexus.kostoed.ru
  resources:
  - routingrules/finalizers
  verbs:
  - update
- apiGroups:
  - nexus.kostoed.ru
  resources:
  - routingrules/status
  verbs:
  - get
  - patch
  - update
