---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - nexus.operators.dev.kostoed.ru
  resources:
  - contentselectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nexus.operators.dev.kostoed.ru
  resources:
  - contentselectors/finalizers
  verbs:
  - update
- apiGroups:
  - nexus.operators.dev.kostoed.ru
  resources:
  - contentselectors/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nexus.operators.dev.kostoed.ru
  resources:
  - privileges
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nexus.operators.dev.kostoed.ru
  resources:
  - privileges/finalizers
  verbs:
  - update
- apiGroups:
  - nexus.operators.dev.kostoed.ru
  resources:
  - privileges/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nexus.operators.dev.kostoed.ru
  resources:
  - repositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nexus.operators.dev.kostoed.ru
  resources:
  - repositories/finalizers
  verbs:
  - update
- apiGroups:
  - nexus.operators.dev.kostoed.ru
  resources:
  - repositories/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nexus.operators.dev.kostoed.ru
  resources:
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nexus.operators.dev.kostoed.ru
  resources:
  - roles/finalizers
  verbs:
  - update
- apiGroups:
  - nexus.operators.dev.kostoed.ru
  resources:
  - roles/status
  verbs:
  - get
  - patch
  - update
