# .chglog/config.yml
style: plain # Упрощенный стиль без группировки по типам
template: template.tpl
options:
  commits:
    filters:
      # Включаем все коммиты, кроме технических (если нужно)
      Type: 
        - feat
        - fix
        - docs
        - perf
        - refactor
  header:
    pattern: "^([\\w\\d]+):\\s(.+)"
    patternMaps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
