# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

env:
  GO_VERSION: '1.23.3'
  GOLANGCILINT_VERSION: 'v1.62.0'

on:
  push:
    branches: [ "master" ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ "master" ]

jobs:

  lint:
      # Only run this on repositories in the 'mkostelcev' org, not on forks.
      if: startsWith(github.repository, 'mkostelcev/')
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: false
      - name: Ensure code formatting and style is consistent
        uses: golangci/golangci-lint-action@v6
        with:
          version: ${{ env.GOLANGCILINT_VERSION }}

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Build
      run: go build -v ./...

  release:
    if: github.event_name == 'push' && 
        (
          startsWith(github.ref, 'refs/tags/v')
          || startsWith(github.ref, 'refs/heads/feature/') # FOR TEST
        )
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Generate CHANGELOG
        run: |
          go install github.com/skywinder/git-chglog/cmd/git-chglog@latest
          git-chglog -o CHANGELOG.md

      - name: Build binaries (linux/amd64, linux/arm64, darwin/amd64, darwin/arm64, windows/amd64)
        run: |
          set -e
          PLATFORMS="linux/amd64 linux/arm64 darwin/amd64 darwin/arm64 windows/amd64"
          for PLATFORM in $PLATFORMS; do
            GOOS=${PLATFORM%/*}
            GOARCH=${PLATFORM#*/}
            BIN_NAME="nexus-operator-${GOOS}-${GOARCH}"
            [ "$GOOS" = "windows" ] && BIN_NAME="$BIN_NAME.exe"
            env GOOS=$GOOS GOARCH=$GOARCH go build -ldflags="-s -w" -o "$BIN_NAME" ./cmd/nexus-operator
            ARCHIVE="${BIN_NAME%.*}.tar.gz"
            tar -czf "$ARCHIVE" "$BIN_NAME"
            rm "$BIN_NAME"
          done

      - name: Create GitHub Release and upload binaries
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.tar.gz
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
